### ISSUE TITLE
[BUG] Default instructions do not work if you use macOS

### ISSUE THREAD

**Issue by antejavor** [memgraph/prometheus-exporter#13]
**Describe the bug**
If you use MacOS you need to change the `host.docker.internal` instead of `localhost` in the `config/prometeus.yaml` 

This: 

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "memgraph-metrics"
    static_configs:
      - targets: ["localhost:9115"]
```

Should be replaced with this: 

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "memgraph-metrics"
    static_configs:
      - targets: ["host.docker.internal:9115"]
```

This should be implemented in the exporter code.
